version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pas123
  test-db:
    image: postgres:alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pas123
